---
version: '3.2'
networks:
  default:
    external:
      name: devstack_default
services:
  meadow:
    image: nulib/meadow
    build:
      context: .
    environment:
      SECRET_KEY_BASE: c/HprlqRq6CxhIysNuGFKvuIJ9LJ73TFzOIhYM3uW2/y3M2EKriDyjDzrbSlnBM0
      DATABASE_URL: ecto://docker:d0ck3r@db/docker
    ports:
      - 4000:4000
